### ISSUE TITLE
Database Planning

### ISSUE THREAD

**Issue by SamuelLabrador** [SamuelLabrador/SecurityTrader#13]
Because the server is stateless we need a database to store data. We may need to store user login data, chat history, and the histories of games. We should research and choose a database best suited for our use case. 

Some details to consider:
- Scalability
- Ease of use
- Integration with Play Framework
- Schema Versioning
- Supported query features
- Performance over time. 
- SQL vs NoSQL

**Comment by SamuelLabrador** [comment]
@miguelandrade4 Good story for you

**Comment by miguelandrade4** [comment]
For the database, I'll prioritize my research to compare commonly used databases compatible with the Play Framework, if none are to meet our criteria, search will be expanded.

**Comment by miguelandrade4** [comment]
If we're looking for ease of use, relational SQL databases are the way to go, with JDBC connection adding databases such as SQLite and PostgreSQL is extremely simple and supported. NoSQL seems to be a different matter as plugin support for Play will need to be made separately. Reference: https://dzone.com/articles/play-nosql-building-nosql

**Comment by miguelandrade4** [comment]
With thoughts of moving our data onto a cloud we have gone with choosing MySQL as our main database platform. We considered SQLite as an alternative but given it's data security flaws, "A database engine that uses a server can, in some instances, provide better protection from bugs in the client application than a serverless database like SQLite" MySQL provides a better incentive for use. We also scalability into our consideration and MySQL works better with what we currently have in mind.
