### ISSUE TITLE
Database Setup

### ISSUE THREAD

**Issue by SamuelLabrador** [SamuelLabrador/SecurityTrader#21]
As a user, I'd like to be able to access my friends list, match history, and private messages. For this persistent functionality to be possible, we need a database.

**Definition of Done**

**Server**
- [ ] Create a database controller that interacts with the database.
- [x] Create a wiki page, detailing how to create a database for development

**Comment by SamuelLabrador** [comment]
This issue is currently blocked by #13. Remove tag when #13 is closed.

**Comment by miguelandrade4** [comment]
Note 1: Look at DA, and controllers Files for database connectivity.
